site_name: Polityka bezpieczeństwa w firmie IT
theme:
  name: material
  palette:
    primary: blue grey
    accent: light blue
nav:
  
Strona główna: index.md
Autorzy: autorzy.md
Teoria: teoria.md
Przykłady: przyklady.md
Wdrożenie: wdrozenie.md